### ISSUE TITLE
ATC button text loosing opacity on click in wishlist

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#11]
Video: https://www.awesomescreenshot.com/video/9067117?key=8fe27477f8a32c414982e4c565b1d915

**Comment by devAlokTripathi** [comment]
@ui-amankumar  please check

**Comment by ui-amankumar** [comment]
@Shoaibans, @devAlokTripathi ATC button opacity issue is coming when we fire on-click event through jS.

**Comment by ui-amankumar** [comment]
@Shoaibans ATC button opacity is not an issue it is worked as a loader to add on cart.
