### ISSUE TITLE
Choose option/ Quick view not coming in search page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#12]
![image](https://user-images.githubusercontent.com/97726944/170033584-a2ee84ea-32ac-4750-b6a6-1d66a85fd020.png)

**Comment by ui-amankumar** [comment]
@devAlokTripathi Please check why it is not coming?

**Comment by ui-amankumar** [comment]
@Shoaibans it is fixed by Raunak.
