### ISSUE TITLE
Review stars are cropping

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#18]
The review stars looks like they are cropping from bottom inside the review app.
![image](https://user-images.githubusercontent.com/97726944/170037473-6ebaf3b6-1b55-4e00-a7be-4d3b16dda31a.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans fixed please check.
![image](https://user-images.githubusercontent.com/100207984/170146707-1210b95e-530d-4607-b0f4-fe4b90277c8f.png)
