### ISSUE TITLE
Homepage Banners size in iPad

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#19]
The banner is looking small in iPad view.
![image](https://user-images.githubusercontent.com/97726944/170037844-c08410ea-819a-461f-b1b4-641440517a74.png)

**Comment by ui-amankumar** [comment]
@Shoaibans Please update what is the issue with this banner?

**Comment by Shoaibans** [comment]
> @Shoaibans Please update what is the issue with this banner?

The banners height is looking small in iPad view @ui-amankumar

**Comment by ui-amankumar** [comment]
@Shoaibans it is set to the Adaptive height, 
Either if we going to fix the height of the banner it is cropping from every side & which is not looking good.
