### ISSUE TITLE
Banner linking

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#2]
The banner is showing women product but the page linked is of Him
![image](https://user-images.githubusercontent.com/97726944/170026557-7c17ef5f-3205-4436-8b7e-09680010bb23.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans fixed please check 
![image](https://user-images.githubusercontent.com/100207984/170105758-73aeff2a-35d8-436f-ab4e-a197364a84f2.png)
