### ISSUE TITLE
Banners size in collection page Header (Mobile & iPad)

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#22]
The banners are looking small in collection page header (Mobile & iPad)
![image](https://user-images.githubusercontent.com/97726944/170039568-98494dfa-346c-4a8a-990c-78c0ce8d166e.png)

**Comment by ui-amankumar** [comment]
@Shoaibans this banner is added on overlay so if we go to add Collection banner for this then we need to add iPad, mobile, and the desktop setting for that so we added overlay banner & it is shown in every device on the same size.
