### ISSUE TITLE
Missing breadcrumbs

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#23]
The breadcrumbs are missing from the store.
![image](https://user-images.githubusercontent.com/97726944/170040353-7324d6a1-8bfa-4031-89d3-2417ec344e98.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans  added 
![image](https://user-images.githubusercontent.com/100207984/170138257-9edbaecd-63d9-4990-81ef-800658b37247.png)
![image](https://user-images.githubusercontent.com/100207984/170138296-9fff856b-31b1-4f20-aa93-eabff7d0c83a.png)

**Comment by devAlokTripathi** [comment]
@ui-amankumar please design it.

**Comment by devAlokTripathi** [comment]
@Shoaibans  please check 
fixed.

**Comment by ui-amankumar** [comment]
@Shoaibans fixed

**Comment by Shoaibans** [comment]
@ui-amankumar we can use dots in breadcrumbs 
![image](https://user-images.githubusercontent.com/97726944/170203614-012728e3-d23a-4a41-ad5d-9a5a897bd042.png)

**Comment by ui-amankumar** [comment]
@Shoaibans It has been fixed now.
