### ISSUE TITLE
Cropped content in product page.

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#24]
The content of the dropdown box is coming cropped.
https://sujkjzkq5q1dbhxy-57779290293.shopifypreview.com/products/to-my-daughter-if-there-ever-comes-a-day-when-we-cant-be-together-keep-me-in-your-heart
![image](https://user-images.githubusercontent.com/97726944/170040733-51d44e65-4611-44c8-8abf-d01e4684418b.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans please check it is fixed.
