### ISSUE TITLE
Spacing between products in cart page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#26]
There is less spacing between the products in cart page.
![image](https://user-images.githubusercontent.com/97726944/170177299-79c4d12c-1df3-47ab-9225-caf51e7ef237.png)

**Comment by ui-amankumar** [comment]
@Shoaibans fixed

**Comment by ui-amankumar** [comment]
@Shoaibans it is fixed now. 
![image](https://user-images.githubusercontent.com/100340113/170207907-5ec5109a-24e3-484e-b9cf-01eb9a56c6e6.png)
