### ISSUE TITLE
Choose option/ Quick view in mobile & iPad

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#29]
The choose option/ Quick view is invisible in mobile & iPad but on clicking the area, quick view pop up is opening.
Video: https://www.awesomescreenshot.com/video/9083700?key=a1818c809713cb6de7a7423642a76209

**Comment by ui-amankumar** [comment]
@Shoaibans fixed
