### ISSUE TITLE
Spacing in footer

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#3]
There is less spacing between about us & policies in footer.
![image](https://user-images.githubusercontent.com/97726944/170028727-fc3b186d-6b2a-4122-ae5b-081e55241ea8.png)

**Comment by devAlokTripathi** [comment]
@ui-amankumar please check.

**Comment by ui-amankumar** [comment]
@Shoaibans Fixed

**Comment by Shoaibans** [comment]
Still coming same 
![image](https://user-images.githubusercontent.com/97726944/170194306-307f468f-a9d4-4a51-afd8-88f3e62a80da.png)

**Comment by ui-amankumar** [comment]
@Shoaibans it is coming this spacing now 
![image](https://user-images.githubusercontent.com/100340113/170194512-217030a3-a782-487d-aa7a-ea1bfd9ea9d3.png)
