### ISSUE TITLE
Arrow buttons spacing in Mac device

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#30]
There is no spacing between the arrow buttons in Mac device (above the testimonials)
![image](https://user-images.githubusercontent.com/97726944/170210874-aa9fc7bd-cc3f-4234-a756-405da30fd4ad.png)

**Comment by ui-amankumar** [comment]
@Shoaibans it is looking good in Mac safari.
![image](https://user-images.githubusercontent.com/100340113/170221426-9a46fb09-2e9d-48ca-8166-413ee7ef47ff.png)
