### ISSUE TITLE
Same products in You may also like section

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#32]
When we are opening a product then that product is also reflecting in You may also like section multiple times.
Pls check the video for the reference.
Video: https://www.awesomescreenshot.com/video/9088752?key=7e044d67f11791ed6e753a5e4a3d1462

**Comment by devAlokTripathi** [comment]
@Shoaibans 
![image](https://user-images.githubusercontent.com/100207984/170314090-5f9c90c9-c751-4860-97a7-f1a5951442f1.png)
fixed please check.
