### ISSUE TITLE
Product page layout is getting changed for some products

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#35]
For some of the products, the layout is getting changed in product page.
https://sisterannsgifts2.com/products/your-personalized-photo-perfect-circle-pendant-wonderful-keepsake-for-any-loved-one?variant=41304809013429
Video: https://www.awesomescreenshot.com/video/9165937?key=8f37b696c30be18959e0c8642b1a0acf

**Comment by ui-amankumar** [comment]
@Shoaibans Client using shineon app for engraving or uploading a photo on some jewellery products She added 307 products.
[products_export_1000_2022-05-30 04 59 05_1653886745.csv](https://github.com/stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22/files/8795799/products_export_1000_2022-05-30.04.59.05_1653886745.csv)
