### ISSUE TITLE
Overlapping issue due to changed layout

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#36]
The arrows and things are overlapping with the header on scrolling.
![image](https://user-images.githubusercontent.com/97726944/170919651-094ea876-7f0c-403b-bb07-5b1e18800268.png)

![image](https://user-images.githubusercontent.com/97726944/170919670-7c87aa5e-d703-4f14-9d1b-7efcd22edfd7.png)

**Comment by ui-amankumar** [comment]
@Shoaibans It is fixed & It is coming from Shinoy apps
