### ISSUE TITLE
The product title is coming very close to the quantity box in cart page (iPad)

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#39]
The product title is coming very close to the quantity box in cart page (iPad)
![image](https://user-images.githubusercontent.com/97726944/170924701-d4585cad-d568-4e66-98dc-679a416929f7.png)

**Comment by ui-amankumar** [comment]
@Shoaibans it is fixed please check
