### ISSUE TITLE
Spacing in sortby filters

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#4]
The filter options are coming very close to the left side of the box. There should be equal spacing on the left and right side.
![image](https://user-images.githubusercontent.com/97726944/170029073-e895a680-2554-48c8-ab12-e31be0e282c8.png)

**Comment by devAlokTripathi** [comment]
@ui-amankumar please check

**Comment by ui-amankumar** [comment]
@Shoaibans this is browser generated feature we cant add spacing to it. 

* See How looking in Mozilla 
![image](https://user-images.githubusercontent.com/100340113/170192372-81c5da37-a536-41cc-86da-20b87b7f7d34.png)
