### ISSUE TITLE
Pagination color combination

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#6]
We can use our store color combination in pagination , it will look good.
https://sujkjzkq5q1dbhxy-57779290293.shopifypreview.com/collections/bracelets
![image](https://user-images.githubusercontent.com/97726944/170029459-fee6a8c1-bbac-4f07-ba03-09a231d6da55.png)

**Comment by ui-amankumar** [comment]
@Shoaibans Fixed
