### ISSUE TITLE
Content cropping in quick view

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#7]
The content is not coming full in quick view pop up.
![image](https://user-images.githubusercontent.com/97726944/170029885-0c252bd7-33a2-4705-bd24-8752f7bcc9a9.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans  fixed please check 
![image](https://user-images.githubusercontent.com/100207984/170110013-1c9a9bae-2322-4271-aa2e-434ce5f47c49.png)

**Comment by ui-amankumar** [comment]
@Shoaibans fixed now
