### ISSUE TITLE
Continue shopping link in cart pop drawer is not working

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#8]
The continue shopping in cart drawer is not working
![image](https://user-images.githubusercontent.com/97726944/170030329-f1dfe98a-9c48-4b8d-a4c3-f848906f02e4.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans  fixed please check 
![image](https://user-images.githubusercontent.com/100207984/170129040-9384cbe7-b027-46f7-9689-3d82bc92a1db.png)

**Comment by ui-amankumar** [comment]
@Shoaibans it is linked to Product page that means it contains all products on the store

**Comment by Shoaibans** [comment]
@devAlokTripathi @ui-amankumar The user should stay to the same page after clicking on continue shopping.
Pls check the video for the reference: https://www.awesomescreenshot.com/video/9083624?key=1012132ce00b9e0ed1d9cc0b567d2ad3

**Comment by ui-amankumar** [comment]
@devAlokTripathi please link that

**Comment by devAlokTripathi** [comment]
@Shoaibans  fixed please check.
