### ISSUE TITLE
Contact form is coming in all the policy pages

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Margaret-Store-Design---26-April-22#9]
Video: https://www.awesomescreenshot.com/video/9067042?key=fea442d6e84be5d72e858d67192a7397

**Comment by devAlokTripathi** [comment]
![image](https://user-images.githubusercontent.com/100207984/170346630-6cc34f44-4d72-4956-ab1f-a1ae8fdf58cc.png)
please check fixed

**Comment by Shoaibans** [comment]
@devAlokTripathi now the contact form is also removed from contact page.
![image](https://user-images.githubusercontent.com/97726944/170411201-de0a9c5d-b2fe-47c6-b18f-0306335c3229.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans fixed please check.
